// ═══════════════════════════════════════════════════════════════
//  繁簡轉換練習 · 數據庫
//  詞組來源：武漢大學文學院古代漢語教學團隊整理（易錯繁簡字對比練習）
//  單字來源：附錄三：部分簡化字與繁體字對照表
// ═══════════════════════════════════════════════════════════════

// ── 詞組數據庫（簡體→繁體詞組對照）────────────────────────────
const PHRASE_DB = [
  // 第一頁
  { simp: "质变", trad: "質變" },
  { simp: "钟爱", trad: "鍾愛" },
  { simp: "钟鼓", trad: "鐘鼓" },
  { simp: "肿胀", trad: "腫脹" },
  { simp: "种类", trad: "種類" },
  { simp: "观众", trad: "觀衆" },
  { simp: "昼夜", trad: "晝夜" },
  { simp: "皱纹", trad: "皺紋" },
  { simp: "烛台", trad: "燭臺" },
  { simp: "构筑", trad: "構築" },
  { simp: "击筑", trad: "擊筑" },
  { simp: "专业", trad: "專業" },
  { simp: "转动", trad: "轉動" },
  { simp: "妆扮", trad: "妝扮" },
  { simp: "庄严", trad: "莊嚴" },
  { simp: "桥桩", trad: "橋樁" },
  { simp: "壮汉", trad: "壯漢" },
  { simp: "坠马", trad: "墜馬" },
  { simp: "浊音", trad: "濁音" },
  { simp: "总统", trad: "總統" },
  { simp: "钻研", trad: "鑽研" },
  // 第二頁
  { simp: "仅仅", trad: "僅僅" },
  { simp: "尽量", trad: "儘量" },
  { simp: "紧张", trad: "緊張" },
  { simp: "进军", trad: "進軍" },
  { simp: "劲头", trad: "勁頭" },
  { simp: "惊叹", trad: "驚嘆" },
  { simp: "竞选", trad: "競選" },
  { simp: "旧闻", trad: "舊聞" },
  { simp: "举报", trad: "舉報" },
  { simp: "剧变", trad: "劇變" },
  { simp: "证据", trad: "證據" },
  { simp: "惧怕", trad: "懼怕" },
  { simp: "觉得", trad: "覺得" },
  { simp: "军队", trad: "軍隊" },
  { simp: "开发", trad: "開發" },
  { simp: "垦荒", trad: "墾荒" },
  { simp: "诚恳", trad: "誠懇" },
  { simp: "抠门", trad: "摳門" },
  { simp: "夸张", trad: "誇張" },
  { simp: "块头", trad: "塊頭" },
  { simp: "宽广", trad: "寬廣" },
  { simp: "亏损", trad: "虧損" },
  { simp: "腊月", trad: "臘月" },
  { simp: "蜡烛", trad: "蠟燭" },
  { simp: "来宾", trad: "來賓" },
  { simp: "兰花", trad: "蘭花" },
  { simp: "拦截", trad: "攔截" },
  { simp: "蓝天", trad: "藍天" },
  { simp: "阅览", trad: "閱覽" },
  { simp: "灿烂", trad: "燦爛" },
  { simp: "劳动", trad: "勞動" },
  { simp: "泪水", trad: "淚水" },
  { simp: "类别", trad: "類別" },
  { simp: "厘米", trad: "釐米" },
  { simp: "离开", trad: "離開" },
  { simp: "礼节", trad: "禮節" },
  { simp: "里层", trad: "裏層" },
  { simp: "邻里", trad: "鄰里" },
  { simp: "历史", trad: "歷史" },
  { simp: "历法", trad: "曆法" },
  { simp: "厉害", trad: "厲害" },
  { simp: "艳丽", trad: "艷麗" },
  { simp: "隶书", trad: "隸書" },
  { simp: "怜爱", trad: "憐愛" },
  { simp: "门帘", trad: "門簾" },
  { simp: "联系", trad: "聯繫" },
  { simp: "敛财", trad: "斂財" },
  { simp: "练习", trad: "練習" },
  { simp: "炼钢", trad: "煉鋼" },
  { simp: "恋爱", trad: "戀愛" },
  { simp: "粮仓", trad: "糧倉" },
  { simp: "两侧", trad: "兩側" },
  { simp: "辽宁", trad: "遼寧" },
  { simp: "疗养", trad: "療養" },
  { simp: "了解", trad: "瞭解" },
  { simp: "了结", trad: "了結" },
  { simp: "猎获", trad: "獵獲" },
  { simp: "邻国", trad: "鄰國" },
  { simp: "临门", trad: "臨門" },
  { simp: "灵动", trad: "靈動" },
  { simp: "岭南", trad: "嶺南" },
  { simp: "刘备", trad: "劉備" },
  { simp: "陆机", trad: "陸機" },
  { simp: "龙凤", trad: "龍鳳" },
  { simp: "楼台", trad: "樓臺" },
  { simp: "卢氏", trad: "盧氏" },
  { simp: "芦苇", trad: "蘆葦" },
  { simp: "庐山", trad: "廬山" },
  { simp: "炉灶", trad: "爐竈" },
  { simp: "卤干", trad: "鹵乾" },
  { simp: "虏获", trad: "虜獲" },
  { simp: "笔录", trad: "筆録" },
  { simp: "屡次", trad: "屢次" },
  { simp: "远虑", trad: "遠慮" },
  { simp: "杂乱", trad: "雜亂" },
  { simp: "论语", trad: "論語" },
  { simp: "罗织", trad: "羅織" },
  { simp: "马车", trad: "馬車" },
  { simp: "买卖", trad: "買賣" },
  { simp: "迈进", trad: "邁進" },
  { simp: "麦子", trad: "麥子" },
  { simp: "脉动", trad: "脈動" },
  { simp: "蛮干", trad: "蠻幹" },
  { simp: "满员", trad: "滿員" },
  { simp: "门后", trad: "門後" },
  { simp: "梦乡", trad: "夢鄉" },
  { simp: "弥补", trad: "彌補" },
  { simp: "面包", trad: "麵包" },
  { simp: "庙宇", trad: "廟宇" },
  { simp: "灭顶", trad: "滅頂" },
  { simp: "亩数", trad: "畝數" },
  { simp: "难办", trad: "難辦" },
  { simp: "恼怒", trad: "惱怒" },
  { simp: "脑门", trad: "腦門" },
  { simp: "热闹", trad: "熱鬧" },
  { simp: "拟声", trad: "擬聲" },
  { simp: "酿造", trad: "釀造" },
  { simp: "鸟笼", trad: "鳥籠" },
  { simp: "聂耳", trad: "聶耳" },
  { simp: "宁静", trad: "寧靜" },
  { simp: "农业", trad: "農業" },
  { simp: "欧洲", trad: "歐洲" },
  { simp: "盘问", trad: "盤問" },
  { simp: "辟谣", trad: "闢謠" },
  { simp: "苹果", trad: "蘋果" },
  { simp: "凭栏", trad: "憑欄" },
  { simp: "泼妇", trad: "潑婦" },
  { simp: "扑灭", trad: "撲滅" },
  { simp: "仆从", trad: "僕從" },
  { simp: "朴学", trad: "樸學" },
  // 第三頁（易錯繁簡字對比練習）
  { simp: "爱护", trad: "愛護" },
  { simp: "碍事", trad: "礙事" },
  { simp: "肮脏", trad: "骯髒" },
  { simp: "棉袄", trad: "棉襖" },
  { simp: "坝顶", trad: "壩頂" },
  { simp: "罢职", trad: "罷職" },
  { simp: "摆动", trad: "擺動" },
  { simp: "裙摆", trad: "裙擺" },
  { simp: "办货", trad: "辦貨" },
  { simp: "帮衬", trad: "幫襯" },
  { simp: "老板", trad: "老闆" },
  { simp: "宝剑", trad: "寶劍" },
  { simp: "报导", trad: "報導" },
  { simp: "备战", trad: "備戰" },
  { simp: "笔势", trad: "筆勢" },
  { simp: "币值", trad: "幣值" },
  { simp: "毕业", trad: "畢業" },
  { simp: "毙命", trad: "斃命" },
  { simp: "边关", trad: "邊關" },
  { simp: "变迁", trad: "變遷" },
  { simp: "标点", trad: "標點" },
  { simp: "表带", trad: "錶帶" },
  { simp: "表扬", trad: "表揚" },
  { simp: "别扭", trad: "彆扭" },
  { simp: "宾馆", trad: "賓館" },
  { simp: "拨转", trad: "撥轉" },
  { simp: "萝卜", trad: "蘿蔔" },
  { simp: "补偿", trad: "補償" },
  { simp: "布阵", trad: "佈陣" },
  { simp: "才刚", trad: "纔剛" },
  { simp: "才华", trad: "才華" },
  { simp: "参与", trad: "參與" },
  { simp: "残废", trad: "殘廢" },
  { simp: "蚕茧", trad: "蠶繭" },
  { simp: "仓库", trad: "倉庫" },
  { simp: "苍劲", trad: "蒼勁" },
  { simp: "层次", trad: "層次" },
  { simp: "侪属", trad: "儕屬" },
  { simp: "搀杂", trad: "攙雜" },
  { simp: "禅师", trad: "禪師" },
  { simp: "缠绕", trad: "纏繞" },
  { simp: "产权", trad: "產權" },
  { simp: "忏悔", trad: "懺悔" },
  { simp: "长寿", trad: "長壽" },
  { simp: "场地", trad: "場地" },
  { simp: "尝试", trad: "嘗試" },
  { simp: "偿还", trad: "償還" },
  { simp: "厂长", trad: "廠長" },
  { simp: "畅达", trad: "暢達" },
  { simp: "车队", trad: "車隊" },
  { simp: "彻底", trad: "徹底" },
  { simp: "尘土", trad: "塵土" },
  { simp: "陈说", trad: "陳説" },
  { simp: "衬衫", trad: "襯衫" },
  { simp: "称号", trad: "稱號" },
  { simp: "惩处", trad: "懲處" },
  { simp: "痴迷", trad: "癡迷" },
  { simp: "迟缓", trad: "遲緩" },
  { simp: "齿轮", trad: "齒輪" },
  { simp: "炽热", trad: "熾熱" },
  { simp: "冲击", trad: "衝擊" },
  { simp: "虫灾", trad: "蟲災" },
  { simp: "宠爱", trad: "寵愛" },
  { simp: "筹备", trad: "籌備" },
  { simp: "丑恶", trad: "醜惡" },
  { simp: "一出", trad: "一齣" },
  { simp: "刍茗", trad: "芻茗" },
  { simp: "处罚", trad: "處罰" },
  { simp: "基础", trad: "基礎" },
  { simp: "触觉", trad: "觸覺" },
  { simp: "传递", trad: "傳遞" },
  { simp: "床板", trad: "牀板" },
  { simp: "唇齿", trad: "唇齒" },
  { simp: "辞职", trad: "辭職" },
  { simp: "聪颖", trad: "聰穎" },
  { simp: "从来", trad: "從來" },
  { simp: "丛书", trad: "叢書" },
  { simp: "窜访", trad: "竄訪" },
  { simp: "达观", trad: "達觀" },
  { simp: "发呆", trad: "發獃" },
  { simp: "带头", trad: "帶頭" },
  { simp: "担当", trad: "擔當" },
  { simp: "单独", trad: "單獨" },
  { simp: "胆识", trad: "膽識" },
  { simp: "当选", trad: "當選" },
  { simp: "党龄", trad: "黨齡" },
  { simp: "导体", trad: "導體" },
  { simp: "岛屿", trad: "島嶼" },
  { simp: "电灯", trad: "電燈" },
  { simp: "邓通", trad: "鄧通" },
  { simp: "籴米", trad: "糴米" },
  { simp: "敌国", trad: "敵國" },
  { simp: "涤荡", trad: "滌蕩" },
  { simp: "递补", trad: "遞補" },
  { simp: "点戏", trad: "點戲" },
  { simp: "东风", trad: "東風" },
  { simp: "动笔", trad: "動筆" },
  { simp: "斗鸡", trad: "鬭雞" },
  // 第四頁
  { simp: "齐国", trad: "齊國" },
  { simp: "启发", trad: "啟發" },
  { simp: "岂敢", trad: "豈敢" },
  { simp: "气体", trad: "氣體" },
  { simp: "弃权", trad: "棄權" },
  { simp: "变迁", trad: "變遷" },
  { simp: "牵头", trad: "牽頭" },
  { simp: "签证", trad: "簽證" },
  { simp: "钱柜", trad: "錢櫃" },
  { simp: "纤夫", trad: "纖夫" },
  { simp: "枪弹", trad: "槍彈" },
  { simp: "墙头", trad: "牆頭" },
  { simp: "乔迁", trad: "喬遷" },
  { simp: "桥梁", trad: "橋樑" },
  { simp: "穷门", trad: "窮門" },
  { simp: "窃听", trad: "竊聽" },
  { simp: "亲临", trad: "親臨" },
  { simp: "寝室", trad: "寢室" },
  { simp: "轻伤", trad: "輕傷" },
  { simp: "庆贺", trad: "慶賀" },
  { simp: "穷尽", trad: "窮盡" },
  { simp: "琼楼", trad: "瓊樓" },
  { simp: "区分", trad: "區分" },
  { simp: "酒曲", trad: "酒麴" },
  { simp: "驱动", trad: "驅動" },
  { simp: "趋势", trad: "趨勢" },
  { simp: "躯体", trad: "軀體" },
  { simp: "权术", trad: "權術" },
  { simp: "劝导", trad: "勸導" },
  { simp: "确实", trad: "確實" },
  { simp: "辞让", trad: "辭讓" },
  { simp: "富饶", trad: "富饒" },
  { simp: "扰乱", trad: "擾亂" },
  { simp: "热恋", trad: "熱戀" },
  { simp: "认识", trad: "認識" },
  { simp: "荣获", trad: "榮獲" },
  { simp: "洒药", trad: "灑藥" },
  { simp: "伞盖", trad: "傘蓋" },
  { simp: "丧礼", trad: "喪禮" },
  { simp: "扫地", trad: "掃地" },
  { simp: "涩苦", trad: "澀苦" },
  { simp: "杀敌", trad: "殺敵" },
  { simp: "晒图", trad: "曬圖" },
  { simp: "单据", trad: "單據" },
  { simp: "伤员", trad: "傷員" },
  { simp: "沈阳", trad: "瀋陽" },
  { simp: "肾脏", trad: "腎臟" },
  { simp: "声响", trad: "聲響" },
  { simp: "绳子", trad: "繩子" },
  { simp: "圣洁", trad: "聖潔" },
  { simp: "胜败", trad: "勝敗" },
  { simp: "师传", trad: "師傳" },
  { simp: "诗坛", trad: "詩壇" },
  { simp: "湿润", trad: "濕潤" },
  { simp: "时钟", trad: "時鐘" },
  { simp: "识货", trad: "識貨" },
  { simp: "实际", trad: "實際" },
  { simp: "势众", trad: "勢衆" },
  { simp: "适当", trad: "適當" },
  { simp: "释义", trad: "釋義" },
  { simp: "寿面", trad: "壽麵" },
  { simp: "兽医", trad: "獸醫" },
  { simp: "书斋", trad: "書齋" },
  { simp: "赎买", trad: "贖買" },
  { simp: "属国", trad: "屬國" },
  { simp: "数学", trad: "數學" },
  { simp: "术语", trad: "術語" },
  { simp: "树干", trad: "樹榦" },
  { simp: "竖笔", trad: "豎筆" },
  { simp: "将帅", trad: "將帥" },
  { simp: "双飞", trad: "雙飛" },
  { simp: "闪烁", trad: "閃爍" },
  { simp: "丝带", trad: "絲帶" },
  { simp: "松开", trad: "鬆開" },
  { simp: "耸立", trad: "聳立" },
  { simp: "苏轼", trad: "蘇軾" },
  { simp: "苏醒", trad: "甦醒" },
  { simp: "严肃", trad: "嚴肅" },
  { simp: "虽说", trad: "雖説" },
  { simp: "随从", trad: "隨從" },
  { simp: "岁数", trad: "歲數" },
  { simp: "孙子", trad: "孫子" },
  { simp: "台阶", trad: "臺階" },
  { simp: "台灯", trad: "檯燈" },
  { simp: "台风", trad: "颱風" },
  { simp: "态势", trad: "態勢" },
  { simp: "体坛", trad: "體壇" },
  { simp: "酒坛", trad: "酒罎" },
  { simp: "县花", trad: "縣花" },
  { simp: "叹气", trad: "嘆氣" },
  { simp: "汤药", trad: "湯藥" },
  { simp: "誊写", trad: "謄寫" },
  { simp: "体检", trad: "體檢" },
  { simp: "条约", trad: "條約" },
  { simp: "籴米", trad: "糴米" },
  { simp: "铁矿", trad: "鐵礦" },
  { simp: "厅长", trad: "廳長" },
  { simp: "听觉", trad: "聽覺" },
  { simp: "头颅", trad: "頭顱" },
  { simp: "图画", trad: "圖畫" },
  { simp: "团结", trad: "團結" },
  { simp: "袜子", trad: "襪子" },
  { simp: "弯曲", trad: "彎曲" },
  { simp: "万岁", trad: "萬歲" },
  { simp: "网鱼", trad: "網魚" },
  { simp: "变为", trad: "變爲" },
  { simp: "围歼", trad: "圍殲" },
  { simp: "卫队", trad: "衛隊" },
  // 第五頁
  { simp: "读书", trad: "讀書" },
  { simp: "独断", trad: "獨斷" },
  { simp: "对应", trad: "對應" },
  { simp: "吨位", trad: "噸位" },
  { simp: "夺取", trad: "奪取" },
  { simp: "儿孙", trad: "兒孫" },
  { simp: "尔时", trad: "爾時" },
  { simp: "发扬", trad: "發揚" },
  { simp: "发型", trad: "髮型" },
  { simp: "范畴", trad: "範疇" },
  { simp: "飞机", trad: "飛機" },
  { simp: "废除", trad: "廢除" },
  { simp: "坟地", trad: "墳地" },
  { simp: "奋进", trad: "奮進" },
  { simp: "丰满", trad: "豐滿" },
  { simp: "风声", trad: "風聲" },
  { simp: "鸾凤", trad: "鸞鳳" },
  { simp: "肤浅", trad: "膚淺" },
  { simp: "抚养", trad: "撫養" },
  { simp: "妇联", trad: "婦聯" },
  { simp: "复兴", trad: "復興" },
  { simp: "复数", trad: "複數" },
  { simp: "盖房", trad: "蓋房" },
  { simp: "干湿", trad: "乾濕" },
  { simp: "干劲", trad: "幹勁" },
  { simp: "赶车", trad: "趕車" },
  { simp: "冈峦", trad: "岡巒" },
  { simp: "刚才", trad: "剛纔" },
  { simp: "岗楼", trad: "崗樓" },
  { simp: "个体", trad: "個體" },
  { simp: "巩固", trad: "鞏固" },
  { simp: "沟涞", trad: "溝淶" },
  { simp: "构图", trad: "構圖" },
  { simp: "购买", trad: "購買" },
  { simp: "谷仓", trad: "穀倉" },
  { simp: "蛊惑", trad: "蠱惑" },
  { simp: "环顾", trad: "環顧" },
  { simp: "刮风", trad: "颳風" },
  { simp: "刮脸", trad: "刮臉" },
  { simp: "关系", trad: "關係" },
  { simp: "观众", trad: "觀衆" },
  { simp: "纶巾", trad: "綸巾" },
  { simp: "广场", trad: "廣場" },
  { simp: "归属", trad: "歸屬" },
  { simp: "龟壳", trad: "龜殼" },
  { simp: "柜台", trad: "櫃檯" },
  { simp: "国际", trad: "國際" },
  { simp: "过节", trad: "過節" },
  { simp: "还钱", trad: "還錢" },
  { simp: "韩国", trad: "韓國" },
  { simp: "汉语", trad: "漢語" },
  { simp: "号称", trad: "號稱" },
  { simp: "吓人", trad: "嚇人" },
  { simp: "轰击", trad: "轟擊" },
  { simp: "后来", trad: "後來" },
  { simp: "胡须", trad: "鬍鬚" },
  { simp: "喷壶", trad: "噴壺" },
  { simp: "护卫", trad: "護衛" },
  { simp: "京沪", trad: "京滬" },
  { simp: "华侨", trad: "華僑" },
  { simp: "画图", trad: "畫圖" },
  { simp: "怀旧", trad: "懷舊" },
  { simp: "欢乐", trad: "歡樂" },
  { simp: "环绕", trad: "環繞" },
  { simp: "词汇", trad: "詞彙" },
  { simp: "汇集", trad: "滙集" },
  { simp: "会议", trad: "會議" },
  { simp: "秽闻", trad: "穢聞" },
  { simp: "荟萃", trad: "薈萃" },
  { simp: "获胜", trad: "獲勝" },
  { simp: "收获", trad: "收穫" },
  { simp: "闯祸", trad: "闖禍" },
  { simp: "讥讽", trad: "譏諷" },
  { simp: "饥饿", trad: "飢餓" },
  { simp: "饥荒", trad: "饑荒" },
  { simp: "机灵", trad: "機靈" },
  { simp: "鸡笼", trad: "雞籠" },
  { simp: "积压", trad: "積壓" },
  { simp: "极端", trad: "極端" },
  { simp: "几何", trad: "幾何" },
  { simp: "几案", trad: "幾案" },
  { simp: "济南", trad: "濟南" },
  { simp: "系扣", trad: "繫扣" },
  { simp: "际遇", trad: "際遇" },
  { simp: "药剂", trad: "藥劑" },
  { simp: "觊觎", trad: "覬覦" },
  { simp: "继续", trad: "繼續" },
  { simp: "夹层", trad: "夾層" },
  { simp: "价钱", trad: "價錢" },
  { simp: "歼灭", trad: "殲滅" },
  { simp: "坚实", trad: "堅實" },
  { simp: "艰难", trad: "艱難" },
  { simp: "监视", trad: "監視" },
  { simp: "贵贱", trad: "貴賤" },
  { simp: "俭朴", trad: "儉樸" },
  { simp: "见识", trad: "見識" },
  { simp: "荐举", trad: "薦舉" },
  { simp: "鉴赏", trad: "鑒賞" },
  { simp: "姜蒜", trad: "薑蒜" },
  { simp: "讲学", trad: "講學" },
  { simp: "奖励", trad: "獎勵" },
  { simp: "将军", trad: "將軍" },
  { simp: "浇灌", trad: "澆灌" },
  { simp: "娇惯", trad: "嬌慣" },
  { simp: "胶水", trad: "膠水" },
  { simp: "阶层", trad: "階層" },
  { simp: "节气", trad: "節氣" },
  { simp: "杰出", trad: "傑出" },
  { simp: "洁净", trad: "潔淨" },
];

// Remove duplicates
const phraseMap = new Map();
PHRASE_DB.forEach(p => {
  const key = p.simp + '→' + p.trad;
  if (!phraseMap.has(key)) phraseMap.set(key, p);
});
const PHRASES = Array.from(phraseMap.values());

// ── 單字數據庫（簡體→繁體字對照，來源：附錄三）──────────────────
const CHAR_DB = [
  { simp: "碍", trad: "礙", alts: [] },
  { simp: "罢", trad: "罷", alts: [] },
  { simp: "摆", trad: "擺", alts: [] },
  { simp: "办", trad: "辦", alts: [] },
  { simp: "帮", trad: "幫", alts: [] },
  { simp: "宝", trad: "寶", alts: [] },
  { simp: "报", trad: "報", alts: [] },
  { simp: "备", trad: "備", alts: [] },
  { simp: "笔", trad: "筆", alts: [] },
  { simp: "币", trad: "幣", alts: [] },
  { simp: "毕", trad: "畢", alts: [] },
  { simp: "毙", trad: "斃", alts: [] },
  { simp: "边", trad: "邊", alts: [] },
  { simp: "变", trad: "變", alts: [] },
  { simp: "标", trad: "標", alts: [] },
  { simp: "宾", trad: "賓", alts: [] },
  { simp: "补", trad: "補", alts: [] },
  { simp: "才", trad: "纔", alts: [] },
  { simp: "蚕", trad: "蠶", alts: [] },
  { simp: "仓", trad: "倉", alts: [] },
  { simp: "层", trad: "層", alts: [] },
  { simp: "产", trad: "産", alts: [] },
  { simp: "谗", trad: "讒", alts: [] },
  { simp: "尝", trad: "嘗", alts: [] },
  { simp: "偿", trad: "償", alts: [] },
  { simp: "厂", trad: "廠", alts: [] },
  { simp: "彻", trad: "徹", alts: [] },
  { simp: "尘", trad: "塵", alts: [] },
  { simp: "衬", trad: "襯", alts: [] },
  { simp: "称", trad: "稱", alts: [] },
  { simp: "惩", trad: "懲", alts: [] },
  { simp: "迟", trad: "遲", alts: [] },
  { simp: "冲", trad: "衝", alts: [] },
  { simp: "虫", trad: "蟲", alts: [] },
  { simp: "丑", trad: "醜", alts: [] },
  { simp: "筹", trad: "籌", alts: [] },
  { simp: "处", trad: "處", alts: [] },
  { simp: "触", trad: "觸", alts: [] },
  { simp: "础", trad: "礎", alts: [] },
  { simp: "刍", trad: "芻", alts: [] },
  { simp: "辞", trad: "辭", alts: [] },
  { simp: "聪", trad: "聰", alts: [] },
  { simp: "丛", trad: "叢", alts: [] },
  { simp: "窜", trad: "竄", alts: [] },
  { simp: "达", trad: "達", alts: [] },
  { simp: "担", trad: "擔", alts: [] },
  { simp: "胆", trad: "膽", alts: [] },
  { simp: "当", trad: "當", alts: [] },
  { simp: "档", trad: "檔", alts: [] },
  { simp: "党", trad: "黨", alts: [] },
  { simp: "导", trad: "導", alts: [] },
  { simp: "灯", trad: "燈", alts: [] },
  { simp: "邓", trad: "鄧", alts: [] },
  { simp: "敌", trad: "敵", alts: [] },
  { simp: "籴", trad: "糴", alts: [] },
  { simp: "递", trad: "遞", alts: [] },
  { simp: "淀", trad: "澱", alts: [] },
  { simp: "点", trad: "點", alts: [] },
  { simp: "垫", trad: "墊", alts: [] },
  { simp: "动", trad: "動", alts: [] },
  { simp: "斗", trad: "鬭", alts: [] },
  { simp: "独", trad: "獨", alts: [] },
  { simp: "断", trad: "斷", alts: [] },
  { simp: "对", trad: "對", alts: [] },
  { simp: "队", trad: "隊", alts: [] },
  { simp: "夺", trad: "奪", alts: [] },
  { simp: "堕", trad: "墮", alts: [] },
  { simp: "尔", trad: "爾", alts: [] },
  { simp: "儿", trad: "兒", alts: [] },
  { simp: "发", trad: "發", alts: ["髮"] },
  { simp: "范", trad: "範", alts: [] },
  { simp: "飞", trad: "飛", alts: [] },
  { simp: "奋", trad: "奮", alts: [] },
  { simp: "粪", trad: "糞", alts: [] },
  { simp: "坟", trad: "墳", alts: [] },
  { simp: "丰", trad: "豐", alts: [] },
  { simp: "凤", trad: "鳳", alts: [] },
  { simp: "妇", trad: "婦", alts: [] },
  { simp: "复", trad: "復", alts: ["複", "覆"] },
  { simp: "肤", trad: "膚", alts: [] },
  { simp: "盖", trad: "蓋", alts: [] },
  { simp: "干", trad: "幹", alts: ["乾"] },
  { simp: "赶", trad: "趕", alts: [] },
  { simp: "个", trad: "個", alts: [] },
  { simp: "巩", trad: "鞏", alts: [] },
  { simp: "沟", trad: "溝", alts: [] },
  { simp: "构", trad: "構", alts: [] },
  { simp: "购", trad: "購", alts: [] },
  { simp: "谷", trad: "穀", alts: [] },
  { simp: "顾", trad: "顧", alts: [] },
  { simp: "关", trad: "關", alts: [] },
  { simp: "观", trad: "觀", alts: [] },
  { simp: "广", trad: "廣", alts: [] },
  { simp: "归", trad: "歸", alts: [] },
  { simp: "龟", trad: "龜", alts: [] },
  { simp: "柜", trad: "櫃", alts: [] },
  { simp: "过", trad: "過", alts: [] },
  { simp: "国", trad: "國", alts: [] },
  { simp: "汉", trad: "漢", alts: [] },
  { simp: "号", trad: "號", alts: [] },
  { simp: "轰", trad: "轟", alts: [] },
  { simp: "后", trad: "後", alts: [] },
  { simp: "护", trad: "護", alts: [] },
  { simp: "沪", trad: "滬", alts: [] },
  { simp: "画", trad: "畫", alts: [] },
  { simp: "划", trad: "劃", alts: [] },
  { simp: "华", trad: "華", alts: [] },
  { simp: "怀", trad: "懷", alts: [] },
  { simp: "坏", trad: "壞", alts: [] },
  { simp: "欢", trad: "歡", alts: [] },
  { simp: "环", trad: "環", alts: [] },
  { simp: "还", trad: "還", alts: [] },
  { simp: "会", trad: "會", alts: [] },
  { simp: "秽", trad: "穢", alts: [] },
  { simp: "汇", trad: "匯", alts: ["彙"] },
  { simp: "伙", trad: "夥", alts: [] },
  { simp: "获", trad: "獲", alts: ["穫"] },
  { simp: "几", trad: "幾", alts: [] },
  { simp: "机", trad: "機", alts: [] },
  { simp: "击", trad: "撃", alts: [] },
  { simp: "际", trad: "際", alts: [] },
  { simp: "剂", trad: "劑", alts: [] },
  { simp: "济", trad: "濟", alts: [] },
  { simp: "挤", trad: "擠", alts: [] },
  { simp: "积", trad: "積", alts: [] },
  { simp: "饥", trad: "饑", alts: [] },
  { simp: "鸡", trad: "鷄", alts: [] },
  { simp: "极", trad: "極", alts: [] },
  { simp: "继", trad: "繼", alts: [] },
  { simp: "价", trad: "價", alts: [] },
  { simp: "艰", trad: "艱", alts: [] },
  { simp: "荐", trad: "薦", alts: [] },
  { simp: "坚", trad: "堅", alts: [] },
  { simp: "歼", trad: "殲", alts: [] },
  { simp: "监", trad: "監", alts: [] },
  { simp: "茧", trad: "繭", alts: [] },
  { simp: "舰", trad: "艦", alts: [] },
  { simp: "鉴", trad: "鍳", alts: [] },
  { simp: "拣", trad: "揀", alts: [] },
  { simp: "讲", trad: "講", alts: [] },
  { simp: "胶", trad: "膠", alts: [] },
  { simp: "借", trad: "藉", alts: [] },
  { simp: "阶", trad: "階", alts: [] },
  { simp: "节", trad: "節", alts: [] },
  { simp: "洁", trad: "潔", alts: [] },
  { simp: "尽", trad: "盡", alts: ["儘"] },
  { simp: "紧", trad: "緊", alts: [] },
  { simp: "仅", trad: "僅", alts: [] },
  { simp: "进", trad: "進", alts: [] },
  { simp: "烬", trad: "燼", alts: [] },
  { simp: "惊", trad: "驚", alts: [] },
  { simp: "竞", trad: "競", alts: [] },
  { simp: "旧", trad: "舊", alts: [] },
  { simp: "举", trad: "舉", alts: [] },
  { simp: "剧", trad: "劇", alts: [] },
  { simp: "据", trad: "據", alts: [] },
  { simp: "惧", trad: "懼", alts: [] },
  { simp: "卷", trad: "捲", alts: [] },
  { simp: "觉", trad: "覺", alts: [] },
  { simp: "开", trad: "開", alts: [] },
  { simp: "垦", trad: "墾", alts: [] },
  { simp: "恳", trad: "懇", alts: [] },
  { simp: "夸", trad: "誇", alts: [] },
  { simp: "块", trad: "塊", alts: [] },
  { simp: "亏", trad: "虧", alts: [] },
  { simp: "扩", trad: "擴", alts: [] },
  { simp: "腊", trad: "臘", alts: [] },
  { simp: "蜡", trad: "蠟", alts: [] },
  { simp: "兰", trad: "蘭", alts: [] },
  { simp: "拦", trad: "攔", alts: [] },
  { simp: "栏", trad: "欄", alts: [] },
  { simp: "烂", trad: "爛", alts: [] },
  { simp: "劳", trad: "勞", alts: [] },
  { simp: "乐", trad: "樂", alts: [] },
  { simp: "类", trad: "類", alts: [] },
  { simp: "累", trad: "纍", alts: [] },
  { simp: "垒", trad: "壘", alts: [] },
  { simp: "里", trad: "裏", alts: [] },
  { simp: "礼", trad: "禮", alts: [] },
  { simp: "丽", trad: "麗", alts: [] },
  { simp: "厉", trad: "厲", alts: [] },
  { simp: "励", trad: "勵", alts: [] },
  { simp: "离", trad: "離", alts: [] },
  { simp: "历", trad: "曆", alts: ["歷"] },
  { simp: "隶", trad: "隸", alts: [] },
  { simp: "帘", trad: "簾", alts: [] },
  { simp: "联", trad: "聯", alts: [] },
  { simp: "恋", trad: "戀", alts: [] },
  { simp: "怜", trad: "憐", alts: [] },
  { simp: "炼", trad: "煉", alts: [] },
  { simp: "练", trad: "練", alts: [] },
  { simp: "粮", trad: "糧", alts: [] },
  { simp: "了", trad: "瞭", alts: [] },
  { simp: "疗", trad: "療", alts: [] },
  { simp: "猎", trad: "獵", alts: [] },
  { simp: "临", trad: "臨", alts: [] },
  { simp: "邻", trad: "鄰", alts: [] },
  { simp: "灵", trad: "靈", alts: [] },
  { simp: "龄", trad: "齡", alts: [] },
  { simp: "岭", trad: "嶺", alts: [] },
  { simp: "刘", trad: "劉", alts: [] },
  { simp: "龙", trad: "龍", alts: [] },
  { simp: "楼", trad: "樓", alts: [] },
  { simp: "娄", trad: "婁", alts: [] },
  { simp: "录", trad: "録", alts: [] },
  { simp: "陆", trad: "陸", alts: [] },
  { simp: "虏", trad: "虜", alts: [] },
  { simp: "卤", trad: "鹵", alts: ["滷"] },
  { simp: "卢", trad: "盧", alts: [] },
  { simp: "庐", trad: "廬", alts: [] },
  { simp: "泸", trad: "瀘", alts: [] },
  { simp: "芦", trad: "蘆", alts: [] },
  { simp: "炉", trad: "爐", alts: [] },
  { simp: "乱", trad: "亂", alts: [] },
  { simp: "罗", trad: "羅", alts: [] },
  { simp: "屡", trad: "屢", alts: [] },
  { simp: "虑", trad: "慮", alts: [] },
  { simp: "驴", trad: "驢", alts: [] },
  { simp: "迈", trad: "邁", alts: [] },
  { simp: "买", trad: "買", alts: [] },
  { simp: "卖", trad: "賣", alts: [] },
  { simp: "麦", trad: "麥", alts: [] },
  { simp: "蛮", trad: "蠻", alts: [] },
  { simp: "么", trad: "麽", alts: [] },
  { simp: "霉", trad: "黴", alts: [] },
  { simp: "梦", trad: "夢", alts: [] },
  { simp: "弥", trad: "彌", alts: [] },
  { simp: "面", trad: "麵", alts: [] },
  { simp: "庙", trad: "廟", alts: [] },
  { simp: "灭", trad: "滅", alts: [] },
  { simp: "亩", trad: "畝", alts: [] },
  { simp: "难", trad: "難", alts: [] },
  { simp: "恼", trad: "惱", alts: [] },
  { simp: "脑", trad: "腦", alts: [] },
  { simp: "拟", trad: "擬", alts: [] },
  { simp: "酿", trad: "釀", alts: [] },
  { simp: "宁", trad: "寧", alts: [] },
  { simp: "农", trad: "農", alts: [] },
  { simp: "欧", trad: "歐", alts: [] },
  { simp: "盘", trad: "盤", alts: [] },
  { simp: "辟", trad: "闢", alts: [] },
  { simp: "苹", trad: "蘋", alts: [] },
  { simp: "凭", trad: "憑", alts: [] },
  { simp: "朴", trad: "樸", alts: [] },
  { simp: "扑", trad: "撲", alts: [] },
  { simp: "齐", trad: "齊", alts: [] },
  { simp: "气", trad: "氣", alts: [] },
  { simp: "启", trad: "啓", alts: [] },
  { simp: "岂", trad: "豈", alts: [] },
  { simp: "千", trad: "韆", alts: [] },
  { simp: "迁", trad: "遷", alts: [] },
  { simp: "签", trad: "簽", alts: ["籤"] },
  { simp: "牵", trad: "牽", alts: [] },
  { simp: "枪", trad: "槍", alts: [] },
  { simp: "乔", trad: "喬", alts: [] },
  { simp: "侨", trad: "僑", alts: [] },
  { simp: "桥", trad: "橋", alts: [] },
  { simp: "壳", trad: "殼", alts: [] },
  { simp: "窍", trad: "竅", alts: [] },
  { simp: "窃", trad: "竊", alts: [] },
  { simp: "亲", trad: "親", alts: [] },
  { simp: "庆", trad: "慶", alts: [] },
  { simp: "穷", trad: "窮", alts: [] },
  { simp: "琼", trad: "瓊", alts: [] },
  { simp: "秋", trad: "鞦", alts: [] },
  { simp: "区", trad: "區", alts: [] },
  { simp: "趋", trad: "趨", alts: [] },
  { simp: "权", trad: "權", alts: [] },
  { simp: "劝", trad: "勸", alts: [] },
  { simp: "确", trad: "確", alts: [] },
  { simp: "让", trad: "讓", alts: [] },
  { simp: "扰", trad: "擾", alts: [] },
  { simp: "热", trad: "熱", alts: [] },
  { simp: "认", trad: "認", alts: [] },
  { simp: "荣", trad: "榮", alts: [] },
  { simp: "洒", trad: "灑", alts: [] },
  { simp: "丧", trad: "喪", alts: [] },
  { simp: "扫", trad: "掃", alts: [] },
  { simp: "杀", trad: "殺", alts: [] },
  { simp: "晒", trad: "曬", alts: [] },
  { simp: "伤", trad: "傷", alts: [] },
  { simp: "舍", trad: "捨", alts: [] },
  { simp: "摄", trad: "攝", alts: [] },
  { simp: "沈", trad: "瀋", alts: [] },
  { simp: "审", trad: "審", alts: [] },
  { simp: "声", trad: "聲", alts: [] },
  { simp: "胜", trad: "勝", alts: [] },
  { simp: "圣", trad: "聖", alts: [] },
  { simp: "绳", trad: "繩", alts: [] },
  { simp: "湿", trad: "濕", alts: [] },
  { simp: "适", trad: "適", alts: [] },
  { simp: "实", trad: "實", alts: [] },
  { simp: "势", trad: "勢", alts: [] },
  { simp: "师", trad: "師", alts: [] },
  { simp: "寿", trad: "壽", alts: [] },
  { simp: "兽", trad: "獸", alts: [] },
  { simp: "数", trad: "數", alts: [] },
  { simp: "术", trad: "術", alts: [] },
  { simp: "树", trad: "樹", alts: [] },
  { simp: "书", trad: "書", alts: [] },
  { simp: "帅", trad: "帥", alts: [] },
  { simp: "双", trad: "雙", alts: [] },
  { simp: "松", trad: "鬆", alts: [] },
  { simp: "苏", trad: "蘇", alts: [] },
  { simp: "虽", trad: "雖", alts: [] },
  { simp: "随", trad: "隨", alts: [] },
  { simp: "岁", trad: "歲", alts: [] },
  { simp: "孙", trad: "孫", alts: [] },
  { simp: "态", trad: "態", alts: [] },
  { simp: "台", trad: "臺", alts: [] },
  { simp: "摊", trad: "攤", alts: [] },
  { simp: "滩", trad: "灘", alts: [] },
  { simp: "坛", trad: "壇", alts: [] },
  { simp: "叹", trad: "嘆", alts: [] },
  { simp: "体", trad: "體", alts: [] },
  { simp: "条", trad: "條", alts: [] },
  { simp: "粜", trad: "糶", alts: [] },
  { simp: "铁", trad: "鐵", alts: [] },
  { simp: "听", trad: "聽", alts: [] },
  { simp: "厅", trad: "廳", alts: [] },
  { simp: "头", trad: "頭", alts: [] },
  { simp: "图", trad: "圖", alts: [] },
  { simp: "团", trad: "團", alts: [] },
  { simp: "万", trad: "萬", alts: [] },
  { simp: "弯", trad: "彎", alts: [] },
  { simp: "网", trad: "網", alts: [] },
  { simp: "为", trad: "爲", alts: [] },
  { simp: "伪", trad: "僞", alts: [] },
  { simp: "韦", trad: "韋", alts: [] },
  { simp: "卫", trad: "衞", alts: [] },
  { simp: "稳", trad: "穩", alts: [] },
  { simp: "务", trad: "務", alts: [] },
  { simp: "无", trad: "無", alts: [] },
  { simp: "雾", trad: "霧", alts: [] },
  { simp: "牺", trad: "犧", alts: [] },
  { simp: "系", trad: "係", alts: ["繫"] },
  { simp: "戏", trad: "戲", alts: [] },
  { simp: "习", trad: "習", alts: [] },
  { simp: "吓", trad: "嚇", alts: [] },
  { simp: "献", trad: "獻", alts: [] },
  { simp: "显", trad: "顯", alts: [] },
  { simp: "宪", trad: "憲", alts: [] },
  { simp: "县", trad: "縣", alts: [] },
  { simp: "向", trad: "嚮", alts: [] },
  { simp: "响", trad: "響", alts: [] },
  { simp: "乡", trad: "鄉", alts: [] },
  { simp: "协", trad: "協", alts: [] },
  { simp: "写", trad: "寫", alts: [] },
  { simp: "胁", trad: "脅", alts: [] },
  { simp: "泻", trad: "瀉", alts: [] },
  { simp: "亵", trad: "褻", alts: [] },
  { simp: "衅", trad: "釁", alts: [] },
  { simp: "兴", trad: "興", alts: [] },
  { simp: "选", trad: "選", alts: [] },
  { simp: "悬", trad: "懸", alts: [] },
  { simp: "寻", trad: "尋", alts: [] },
  { simp: "逊", trad: "遜", alts: [] },
  { simp: "压", trad: "壓", alts: [] },
  { simp: "艳", trad: "艷", alts: [] },
  { simp: "严", trad: "嚴", alts: [] },
  { simp: "盐", trad: "鹽", alts: [] },
  { simp: "厌", trad: "厭", alts: [] },
  { simp: "养", trad: "養", alts: [] },
  { simp: "样", trad: "様", alts: [] },
  { simp: "阳", trad: "陽", alts: [] },
  { simp: "尧", trad: "堯", alts: [] },
  { simp: "钥", trad: "鑰", alts: [] },
  { simp: "药", trad: "藥", alts: [] },
  { simp: "叶", trad: "葉", alts: [] },
  { simp: "业", trad: "業", alts: [] },
  { simp: "医", trad: "醫", alts: [] },
  { simp: "义", trad: "義", alts: [] },
  { simp: "仪", trad: "儀", alts: [] },
  { simp: "艺", trad: "藝", alts: [] },
  { simp: "亿", trad: "億", alts: [] },
  { simp: "忆", trad: "憶", alts: [] },
  { simp: "隐", trad: "隠", alts: [] },
  { simp: "阴", trad: "陰", alts: [] },
  { simp: "蝇", trad: "蠅", alts: [] },
  { simp: "应", trad: "應", alts: [] },
  { simp: "营", trad: "營", alts: [] },
  { simp: "拥", trad: "擁", alts: [] },
  { simp: "佣", trad: "傭", alts: [] },
  { simp: "踊", trad: "踴", alts: [] },
  { simp: "优", trad: "優", alts: [] },
  { simp: "犹", trad: "猶", alts: [] },
  { simp: "邮", trad: "郵", alts: [] },
  { simp: "忧", trad: "憂", alts: [] },
  { simp: "余", trad: "餘", alts: [] },
  { simp: "御", trad: "禦", alts: [] },
  { simp: "郁", trad: "鬱", alts: [] },
  { simp: "与", trad: "與", alts: [] },
  { simp: "誉", trad: "譽", alts: [] },
  { simp: "屿", trad: "嶼", alts: [] },
  { simp: "远", trad: "遠", alts: [] },
  { simp: "园", trad: "園", alts: [] },
  { simp: "跃", trad: "躍", alts: [] },
  { simp: "云", trad: "雲", alts: [] },
  { simp: "运", trad: "運", alts: [] },
  { simp: "酝", trad: "醖", alts: [] },
  { simp: "杂", trad: "雜", alts: [] },
  { simp: "赃", trad: "贓", alts: [] },
  { simp: "灶", trad: "竈", alts: [] },
  { simp: "凿", trad: "鑿", alts: [] },
  { simp: "枣", trad: "棗", alts: [] },
  { simp: "斋", trad: "齋", alts: [] },
  { simp: "战", trad: "戰", alts: [] },
  { simp: "毡", trad: "氈", alts: [] },
  { simp: "赵", trad: "趙", alts: [] },
  { simp: "这", trad: "這", alts: [] },
  { simp: "折", trad: "摺", alts: [] },
  { simp: "征", trad: "徵", alts: [] },
  { simp: "证", trad: "證", alts: [] },
  { simp: "郑", trad: "鄭", alts: [] },
  { simp: "帜", trad: "幟", alts: [] },
  { simp: "只", trad: "祗", alts: ["隻"] },
  { simp: "职", trad: "職", alts: [] },
  { simp: "制", trad: "製", alts: [] },
  { simp: "执", trad: "執", alts: [] },
  { simp: "质", trad: "質", alts: [] },
  { simp: "种", trad: "種", alts: [] },
  { simp: "众", trad: "衆", alts: [] },
  { simp: "钟", trad: "鐘", alts: ["鍾"] },
  { simp: "肿", trad: "腫", alts: [] },
  { simp: "昼", trad: "晝", alts: [] },
  { simp: "朱", trad: "硃", alts: [] },
  { simp: "筑", trad: "築", alts: [] },
  { simp: "烛", trad: "燭", alts: [] },
  { simp: "专", trad: "專", alts: [] },
  { simp: "庄", trad: "莊", alts: [] },
  { simp: "桩", trad: "樁", alts: [] },
  { simp: "准", trad: "準", alts: [] },
  { simp: "浊", trad: "濁", alts: [] },
  { simp: "总", trad: "總", alts: [] },
  { simp: "纵", trad: "縱", alts: [] },
  { simp: "钻", trad: "鑽", alts: [] },
];

// Export
if (typeof module !== 'undefined') {
  module.exports = { PHRASES, CHAR_DB };
}
